### ISSUE TITLE
Tiles are not loaded correctly with projection of 4326 and tile size of 512

### ISSUE THREAD

**Issue by exotfboy** [maptalks/maptalks.js#1357]
Maptalks 0.49.4, Chrome on windows.

----

We tried to load tiles under projection 4326, and the tile size is 512x512, so we tried the following:

```
    map = new maptalks.Map('mapCon', {
      center: [0, 0],
      zoom: 2,
      minZoom: 1,
      maxZoom: 20,
      spatialReference: {
        projection: 'EPSG:4326'
      },
      baseLayer: new maptalks.TileLayer('base', {
        tileSize: [512, 512],
        tileSystem: [1, -1, -180, 90],
        urlTemplate: 'https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/tile/{z}/{y}/{x}',
      })
    });
```
However the tiles are not loaded correctly, [live demo](https://jsfiddle.net/z35j7fwu/).

How to solve that?

**Comment by fuzhenn** [comment]
It's usually caused by incorrect value of tileSize and tileSystem.
For arcgis service, there is a simpler way to initiate: [the jsfiddle demo](https://jsfiddle.net/fuzhenn/0L2b8zs6/2/).

And also see [the example on maptalks.org](https://maptalks.org/examples/en/tilelayer-projection/arcgis-tile/#tilelayer-projection_arcgis-tile)

**Comment by exotfboy** [comment]
Sounds like I miss the `resolutions` option.
