### ISSUE TITLE
Inner polygon not always visible when using transparency

### ISSUE THREAD

**Issue by INTARYNX** [maptalks/maptalks.js#1923]
maptalks v1.0.0-rc.18 +maptalks.three v0.35.2
Edge 111.0.1661.54 / Firefox 111.0.1

----
When using transparency, a smaller object inside a larger object is not always visible when moving around the scene.

Is there a setting that could help solve this problem?

![image](https://user-images.githubusercontent.com/60597029/229095054-282bdb96-6aa8-40ae-a133-611377084449.png)

----
[**Example on codepen**](https://codepen.io/INTARYNX/pen/ExezrNL)
----

**Comment by fuzhenn** [comment]
It's caused by the rendering order inside THREE.js, when the larger one is rendered before the smaller one, smaller one will be considered to be occluded by the larger one.

A solution is to set the rendeOrder of Object3D object to force THREE to always render the smaller one before the larger one.

https://discourse.threejs.org/t/easiest-way-to-set-rendering-order-for-transparent-objects/25372

**Comment by INTARYNX** [comment]
Thanks for your quick response, it was very helpful, although I couldn't get the renderOrder to work (not sure where to set it), using "depthWrite: false" on the larger object material migitated the problem. I found some useful information about this at https://stackoverflow.com/questions/15994944/transparent-objects-in-three-js
