### ISSUE TITLE
maptalks的DrawTool工具对平板下的双击结束事件处理异常

### ISSUE THREAD

**Issue by DragonEmperorG** [maptalks/maptalks.js#560]
**maptalks's version and what browser you use?**
"maptalks": "^0.35.1", Chrome

**Issue description**
maptalks的DrawTool工具在windows平板上以"LineString"模式绘制线，在双击结束编辑的时候，会出现类似小尾巴的多余的线段。。。
![1awd g x 85brft d 6](https://user-images.githubusercontent.com/24807062/33753916-dca82ba6-dc24-11e7-872b-c218b2e52025.png)

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by axmand** [comment]
一般来说这是因为，touch的双击操作时间间隔要大于鼠标的双击时间间隔，模拟dbclick的操作间隔可能针对人手双击touch不够，故而识别成多次操作

**Comment by fuzhenn** [comment]
Yes, on mobile devices, `click` and `dblclick` events are simulated by `touch` events.
The unwanted tails of drawn lines may be caused by difference between real `dblclick` and simulated 'dblclick`.
I will take some time to reproduce on cellphone and see if any improvements can be made to fix this issue.
