### ISSUE TITLE
draw a  rectangle  and edit , the shape can change to polygon with the edge more than 4

### ISSUE THREAD

**Issue by lifefriend** [maptalks/maptalks.js#630]
**maptalks's version and what browser you use?**

maptalks v0.39.1

**Issue description**

if draw a  rectangle  and edit  it , the shape can change to polygon with the edge more than 4

but if create  a  rectangle  with code(new maptalks.Rectangle) and edit ,the shape remains unchanged

mybe the value  "geometry instanceof Rectangle" in  "GeometryEditor.prototype.start" is different

**Please provide a reproduction URL (on any jsfiddle like site)**

**Comment by fuzhenn** [comment]
Glad to hear from you.

It is on purpose. Since v0.39.0, when DrawTool's mode is set to `Rectangle`, a `maptalks.Polygon` is generated by DrawTool instead of a `maptalks.Rectangle`.

It is because `maptalks.Rectangle` doesn't have a rotation property, and can't rotate with map. It makes it look weird when DrawTool draws a `maptalks.Rectangle` on a rotating map.

Anyway, your opinion does make sense, but before turning back to `maptalks.Rectangle` we need to solve the weird rectangle on rotating map problem.

I think we may consider to add a rotation property to `maptalks.Rectangle` to make it able to rotate.

Any comment?

**Comment by fuzhenn** [comment]
closing, will reopen if necessary
