### ISSUE TITLE
Polygon vertices with varying altitudes

### ISSUE THREAD

**Issue by cornelius-agrippa** [maptalks/maptalks.js#807]
**Issue description**
Hello there, I have a polygon that is defined by vertices with different altitudes (in meters). However I'm not sure how I could draw them in maptalks to make a polygon with varying altitude.
```
{
    "type": "FeatureCollection",
    "name": "Beach Triangle",
    "crs":
    {
        "type": "name",
        "properties":
        {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    },
    "features": [
    {
        "type": "Feature",
        "geometry":
        {
            "type": "Polygon",
            "coordinates": [
                [
                    [-8.792406769419388, 40.489651995769094, 5.18843412399292],
                    [-8.792406207972336, 40.489692987136024, 5.251388072967529],
                    [-8.792362976549288, 40.489669075508353, 5.668316841125488],
                    [-8.792406769419388, 40.489651995769094, 5.18843412399292]
                ]
            ]
        }
    }]
}
```
What would be the best way to draw it? I was reading about it in this page, http://maptalks.org/examples/en/3d/polygon-altitude/#3d_polygon-altitude, but by providing providing an altitude in the properties it affects the whole polygon.

I hope this isn't a silly question, I'm still pretty new to maptalks.
Thanks

**Comment by fuzhenn** [comment]
Hi, @cornelius-agrippa , glad to have you here.

maptalks.js core doesn't support this form of data now, because it's mainly based on Canvas 2D and is lack of ability to render 3d objects.

You can take a look at [maptalks.three](https://github.com/maptalks/maptalks.three/) plugin, in which you can convert the [x, y, z] to THREE Vector by following:

* convert meter distance to three Vector by [`distanceToVector3`](https://github.com/maptalks/maptalks.three/blob/master/index.js#L72)
* convert your xyz to THREE Vector by [`coordinateToVector3`](https://github.com/maptalks/maptalks.three/blob/master/index.js#L57) and z is the above vector.

And then you can use THREE to create a geometry with the vectors as you wish.

Hope this help.

**Comment by cornelius-agrippa** [comment]
Hello!

Thank you very much, [maptalks.three](https://github.com/maptalks/maptalks.three/) was really helpful. I ended up doing exactly what you suggested. Going to post what I ended up with as it might be useful to someone with the same question:

```javascript
var layers = {};
layers.tin = new maptalks.ThreeLayer('TIN');

layers.tin.prepareToDraw = function(gs, scene, camera) {
    var material = new THREE.MeshPhongMaterial([...]);

    var light = new THREE.AmbientLight(0x909090, 1.0);
    scene.add(light);

    var pointLight = new THREE.PointLight(0x909090);
    var lightPos = this.coordinateToVector3([...]);
    pointLight.position.set([...]);
    scene.add(pointLight);

    for (var f in geojson.features) {
        var geometry = new THREE.Geometry();
        var vertices = geojson.features[f].geometry.coordinates[0];

        for (var v in vertices) {
            var altitude = this.distanceToVector3(0, vertices[v][2])
            var vertex   = this.coordinateToVector3({ x: vertices[v][0], y: vertices[v][1]}, altitude.y);
            geometry.vertices.push(vertex);
        }

        geometry.faces.push(new THREE.Face3(0, 1, 2));

        scene.add(new THREE.Mesh(geometry, material));
    }

    layers.tin.renderScene();
}
```

Thank you for your work on Maptalks as-well, I'm enjoying it :).

**Comment by deyihu** [comment]
https://codepen.io/deyihu/pen/XWLzYjW?editors=1010
